---
# tasks file for afonsog.k8s_jenkins

- set_fact:
    tun_pid_file: /tmp/helm_pid

- block:
    - name: set up a tunnel to tiller
      shell: |
        tiller_pod="$(kubectl --namespace=kube-system --selector app=helm,name=tiller get pods --output=jsonpath='{.items[*].metadata.name}')"
        nohup kubectl port-forward "$tiller_pod" 44134:44134 --namespace kube-system </dev/null >/dev/null 2>&1 &
        echo "$!" >{{ tun_pid_file|quote }}
      args:
        creates: "{{ tun_pid_file }}"
      changed_when: false

    - name: install Jenkins via helm
      helm:
        chart:
          name: jenkins
          version: "{{ jenkins_version }}"
          source:
            type: repo
            location: https://kubernetes-charts.storage.googleapis.com
        state: "{{ 'present' if jenkins_enabled else 'purged' }}"
        name: jenkins
        namespace: jenkins
        values: "{{ jenkins_values }}"

  always:
    - name: tear down the tunnel to tiller
      shell: |
        kill "$(cat {{ tun_pid_file|quote }})" || true
        rm -f {{ tun_pid_file|quote }}
      args:
        removes: "{{ tun_pid_file }}"
      changed_when: false
